run:
  go: 1.23
  timeout: 1m

linters:
  enable:
    - asciicheck
    # - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - gocognit
    - gocyclo
    # - gofmt // use gofumpt instead
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - durationcheck
    # - forbidigo
    - forcetypeassert
    - importas
    - nilerr
    - predeclared
    - thelper
    - tparallel
    - wastedassign
    - promlinter
    - bodyclose
    - dupl
    - godot
    - funlen
    - wsl
    # - gochecknoglobals
    # - gochecknoinits
    # - goconst
    - gocritic
    # - godox
    # - goerr113
    # - gosec
    # - noctx
    # - prealloc
    - stylecheck
    # - testpackage
    - cyclop
    - errorlint
    # - nlreturn
    - revive
    # - tagliatelle
    - unparam

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen